---
- name: "labocbz.prepare_host"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Prepare-Host.git"
  version: "2.0"

- name: "labocbz.add_certificates"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Add-Certificates.git"
  version: "2.0"

- name: "labocbz.install_docker"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Docker.git"
  version: "5.0"

- name: "labocbz.install_apache"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Install-Apache.git"
  version: "3.1"

- name: "labocbz.add_apache_confs"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Add-Apache-Confs.git"
  version: "3.1"

- name: "labocbz.add_apache_confs"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Add-Apache-Confs.git"
  version: "3.1"

- name: "labocbz.add_logrotate_confs"
  src: "https://github.com/CBZ-D-velop/Ansible-Role-Labocbz-Add-Logrotate-Confs.git"
  version: "2.1"
